name: "PROD DEPLOY"

on:
    push:
        branches:
        - main

permissions:
    id-token: write
    contents: read

jobs:  
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: "prod"
            aws-assume-role-arn: "arn:aws:iam::497924967799:role/github-actions-Guilhermesadev-pipeline"
            aws-region: "us-east-2"
            aws-statefile-s3-bucket: "guilhermesadev-us-east-2-terraform-satefile"
            aws-lock-dynamodb-table: "guilhermesadev-us-east-2-terraform-lock"